# Generated by Django 4.1.5 on 2023-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
