# Generated by Django 4.1.5 on 2023-06-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_destination_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='categories',
            field=models.CharField(default=int, max_length=100),
            preserve_default=False,
        ),
    ]
